apiVersion: v1
kind: Service
metadata:
  name: opt-domain-prompt-app
  namespace: opt-dev
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: http
  selector:
    app: opt-domain-prompt-app
  sessionAffinity: None
  type: ClusterIP