apiVersion: apps/v1
kind: Deployment
metadata:
  name: opt-be-task-email
  namespace: opt-dev
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: opt-be-task-email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opt-be-task-email
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: opt-be-task-email
        stack: optimality
      annotations:
        dapr.io/enabled: 'true'
        dapr.io/app-id: 'opt-be-task-email'
        dapr.io/app-port: '8080'
        dapr.io/sidecar-liveness-probe-delay-seconds: '10'
        dapr.io/sidecar-liveness-probe-timeout-seconds: '5'
        dapr.io/sidecar-liveness-probe-period-seconds: '20'
        dapr.io/sidecar-readiness-probe-delay-seconds: '10'
        dapr.io/sidecar-readiness-probe-timeout-seconds: '5'
        dapr.io/sidecar-readiness-probe-period-seconds: '20'
    spec:
      containers:
      - name: opt-be-task-email
        image: optimality.azurecr.io/opt-be-task-email:dev-0.0.1-1731051934-8 # {"$imagepolicy": "flux-system:opt-be-task-email"}
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: opt-be-task-email
        - secretRef:
            name: opt-openai
        - secretRef:
            name: opt-azure-app-bot
        - secretRef:
            name: opt-jira
        - secretRef:
            name: opt-elastic-apm
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 1Gi
