apiVersion: v1
kind: ConfigMap
metadata:
  name: opt-be-graph-arangodb
  namespace: opt-dev 
data:
  # Common configs
  ELASTIC_APM_SERVICE_NAME: "opt-be-graph-arangodb"
  NODE_ENV: "production"

  # Dapr configs
  DISALLOW_DAPR: "false"
  DAPR_HOST : "localhost"
  DAPR_PORT: "3500"
  SERVER_HOST: "localhost"
  SERVER_PORT: "3000"
  SECRET_STORE: "azurekeyvault"
  
  #COMMAND_HANDLERS_APP
  CH_DAPR_HOST: "localhost"
  CH_DAPR_PORT: "3500"
  CH_SERVER_HOST: "localhost"
  CH_SERVER_PORT: "3000"
  COMMAND_HANDLERS_APP_PORT: "5004"
  
  #QUERY_HANDLERS_APP
  QH_DAPR_HOST: "localhost"
  QH_DAPR_PORT: "3500"
  QH_SERVER_HOST: "localhost"
  QH_SERVER_PORT: "3000"
  QUERY_HANDLERS_APP_PORT: "5005"
  
  # ArangoDB configs
  ARANGO_URL: "https://arangodb.dev.optimality-pro.ai"
  ARANGO_DB_NAME: "optimality"
  ARANGO_USERNAME: "root"
  ARANGO_PASSWORD: "_}g6)|l%SlSR:|ub;AUX"
