---
apiVersion: v1
kind: Namespace
metadata:
  name: azure-workload-identity-system
spec:
  finalizers:
  - kubernetes
---

apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: azure-workload-identity
  namespace: azure-workload-identity-system
spec:
  interval: 24h
  url: https://azure.github.io/azure-workload-identity/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: workload-identity-webhook
  namespace: azure-workload-identity-system
spec:
  targetNamespace: azure-workload-identity-system
  upgrade:
    preserveValues: false
  install:
    createNamespace: true
  interval: 30m
  chart:
    spec:
      chart: workload-identity-webhook
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: azure-workload-identity
        namespace: azure-workload-identity-system
      interval: 12h
  values:
    fullnameOverride: workload-identity-webhook
    azureTenantID: 19cd252c-b188-4d97-96dd-c74217c18f6d
    replicaCount: 1