apiVersion: v1
kind: ConfigMap
metadata:
  name: opt-be-arangodb-agent
  namespace: opt-dev
data:
  ELASTIC_APM_SERVICE_NAME: "opt-be-arangodb-agent"
  PORT: "8000"
  DAPR_APP_ID: "opt-be-arangodb-agent"
  DAPR_HOST : "localhost"
  DAPR_PORT: "3500"
  ROOT_PATH: "/agent/arangodb"
  MONGODB_URI: "mongodb+srv://optadmin:ntGWV9tgKAp7NHqJQGmLPZrq@opt-core-dev-ncus-pl-0.zfdut.mongodb.net/?retryWrites=true&w=majority&appName=opt-core-dev-ncus"
  OPTI_CHAT_DB_NAME: "chat"
  REDIS_URI: "redis://redis-stack-server.opt-dev.svc.cluster.local.:6379/0"