apiVersion: v1
kind: Service
metadata:
  name: opt-be-arangodb-agent
  namespace: opt-dev
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: http
  selector:
    app: opt-be-arangodb-agent
  sessionAffinity: None
  type: ClusterIP