apiVersion: apps/v1
kind: Deployment
metadata:
  name: opt-domain-rag-search-tag
  namespace: opt-dev
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: opt-domain-rag-search-tag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opt-domain-rag-search-tag
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: opt-domain-rag-search-tag
        stack: optimality
      annotations:
        dapr.io/enabled: 'true'
        dapr.io/app-id: 'opt-domain-rag-search-tag'
        dapr.io/app-port: '5070'
    spec:
      containers:
      - name: opt-domain-rag-search-tag
        image: optimality.azurecr.io/opt-domain-rag-search-tag:dev-0.0.1-1729606406-5 # {"$imagepolicy": "flux-system:opt-domain-rag-search-tag"}
        envFrom:
        - configMapRef:
            name: opt-domain-rag-search-tag
        - configMapRef:
            name: opt-general
        - secretRef:
            name: opt-elasticsearch
        - secretRef:
            name: opt-elastic-apm
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5070
          name: http
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: http
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: http
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 1Gi
