apiVersion: v1
kind: Service
metadata:
  name: opt-domain-rag-search-tag
  namespace: opt-dev
spec:
  ports:
    - protocol: TCP
      port: 5070
      targetPort: 5070
  selector:
    app: opt-domain-rag-search-tag
  sessionAffinity: None
  type: ClusterIP
