apiVersion: v1
kind: ConfigMap
metadata:
  name: opt-domain-user-backend
  namespace: opt-dev 
data:
  # Common configs
  ELASTIC_APM_SERVICE_NAME: "opt-domain-user-backend"
  NODE_ENV: "production"

  # Dapr configs
  DAPR_APP_ID: "opt-domain-user-backend"
  DAPR_HOST : "localhost"
  DAPR_PORT: "3500"
  SERVER_HOST: "localhost"
  SERVER_PORT: "3000"
  SECRET_STORE: "azurekeyvault"
  
  # Database Configuration
  DB_HOST: "opt-pg-core-dev-ncus.postgres.database.azure.com"
  DB_PORT: "5432"
  DB_USER: "optadmin"
  DB_PASS_SECRET_NAME: "opt-pg-core-password"
  DB_NAME: "optimality"
  
  # Dendrite Configuration
  DENDRITE_BASE_URL: "https://dendrite.optimalitypro.com/_matrix/client/r0"

