---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kube-arangodb
  namespace: opt-arangodb
spec:
  interval: 24h
  url: https://arangodb.github.io/kube-arangodb
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-arangodb
  namespace: opt-arangodb
spec:
  targetNamespace: opt-arangodb
  upgrade:
    preserveValues: false
  install:
    createNamespace: true
  interval: 30m
  chart:
    spec:
      chart: kube-arangodb
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: kube-arangodb
        namespace: opt-arangodb
      interval: 12h