---
apiVersion: v1
kind: Namespace
metadata:
  name: dapr-system
spec:
  finalizers:
  - kubernetes
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: dapr
  namespace: dapr-system
spec:
  interval: 24h
  url: https://dapr.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dapr
  namespace: dapr-system
spec:
  targetNamespace: dapr-system
  upgrade:
    preserveValues: false
  install:
    createNamespace: true
  interval: 30m
  chart:
    spec:
      chart: dapr
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: dapr
        namespace: dapr-system
      interval: 12h
  values:
    dapr_placement:
      metadataEnabled: false
    global:
      ha:
        enabled: false