apiVersion: v1
kind: ConfigMap
metadata:
  name: opt-domain-theme-backend
  namespace: opt-dev 
data:
  # Common configs
  ELASTIC_APM_SERVICE_NAME: "opt-domain-theme-backend-command"
  NODE_ENV: "production"

  # Dapr configs
  DISALLOW_DAPR: "false"
  DAPR_HOST : "localhost"
  DAPR_PORT: "3500"
  SERVER_HOST: "localhost"
  SERVER_PORT: "3000"
  SECRET_STORE: "azurekeyvault"
  DB_PASS_SECRET_NAME: "opt-pg-core-password"
  
  # COMMAND_HANDLERS_APP
  CH_DAPR_HOST: "localhost"
  CH_DAPR_PORT: "3500"
  CH_SERVER_HOST: "localhost"
  CH_SERVER_PORT: "3000"
  COMMAND_HANDLERS_APP_PORT: "5004"
  
  # QUERY_HANDLERS_APP
  QH_DAPR_HOST: "localhost"
  QH_DAPR_PORT: "3500"
  QH_SERVER_HOST: "localhost"
  QH_SERVER_PORT: "3000"
  QUERY_HANDLERS_APP_PORT: "5005"

  # Write database configs
  WRITE_DB_HOST: "opt-pg-core-dev-ncus.postgres.database.azure.com"
  WRITE_DB_PORT: "5432"
  WRITE_DB_USERNAME: "optadmin"
  WRITE_DB_PASSWORD: "pjwJslt1Sea2snIsxjFxGL2c799EU1wF"
  WRITE_DB_NAME: "optimality"
  WRITE_DB_SCHEMA: "themes"

  # EventstoreDB configs
  ESDB_CONNECTION_STRING: "esdb://admin:yZ4t7jWMrSNpRV7rFCAXjswY@eventstore.opt-dev.svc.cluster.local.:2113?tls=true&tlsCaFile=eventstore.crt" 
  
  # ReadDB configs
  READ_DB_CONNECTION_STRING: "mongodb+srv://optadmin:ntGWV9tgKAp7NHqJQGmLPZrq@opt-core-dev-ncus-pl-0.zfdut.mongodb.net/themes?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000"
