apiVersion: v1
kind: Service
metadata:
  name: opt-domain-endeavors-backend-query
  namespace: opt-dev
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: opt-domain-endeavors-backend-query
  sessionAffinity: None
  type: ClusterIP
