apiVersion: apps/v1
kind: Deployment
metadata:
  name: opt-domain-theme-app
  namespace: opt-dev
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: opt-domain-theme-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opt-domain-theme-app
  template:
    metadata:
      labels:
        app: opt-domain-theme-app
        stack: optimality
      annotations:
        dapr.io/enabled: 'true'
        dapr.io/app-id: 'opt-domain-theme-app'
        dapr.io/app-port: '3000'
        dapr.io/sidecar-liveness-probe-delay-seconds: '10'
        dapr.io/sidecar-liveness-probe-timeout-seconds: '5'
        dapr.io/sidecar-liveness-probe-period-seconds: '20'
        dapr.io/sidecar-readiness-probe-delay-seconds: '10'
        dapr.io/sidecar-readiness-probe-timeout-seconds: '5'
        dapr.io/sidecar-readiness-probe-period-seconds: '20'
    spec:
      containers:
      - name: opt-domain-theme-app
        image: optimality.azurecr.io/opt-domain-theme-app:dev-0.0.1-1733406370-79 # {"$imagepolicy": "flux-system:opt-domain-theme-app"}
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: opt-domain-theme-app
        - secretRef:
            name: opt-elastic-apm
        ports:
        - containerPort: 3000
          name: http
        readinessProbe:
          httpGet:
            path: /theme
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /theme
            port: http
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
