apiVersion: v1
kind: ConfigMap
metadata:
  name: opt-domain-content-backend
  namespace: opt-dev 
data:
  DAPR_APP_ID: "opt-domain-content-backend"
  DAPR_HOST : "localhost"
  DAPR_PORT: "3500"
  SERVER_HOST: "localhost"
  SERVER_PORT: "3000"
  SECRET_STORE: "azurekeyvault"
  AZURE_STORAGE_ACCOUNT_NAME: "optimalityproadls"
  # TODO: move to secrets
  AZURE_STORAGE_ACCOUNT_KEY: "gTUK0HKz/NUVeW8itrO/pCjSUSRZ2Bk+Ijw9XWGhnHatIGDuAUGGUISQ/Sfgz1DglEWkQeynTskf+AStGI4Mtw=="
  AZURE_STORAGE_CONTAINER_NAME: "content-uploads"
  NODE_ENV: "production"
  ELASTIC_APM_SERVICE_NAME: "opt-domain-content-backend"
  # Database Configuration
  DB_HOST: "opt-pg-core-dev-ncus.postgres.database.azure.com"
  DB_PORT: "5432"
  DB_USER: "optadmin"
  DB_PASS_SECRET_NAME: "opt-pg-core-password"
  DB_NAME: "optimality"