---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingressgw-internal
  namespace: istio-system
spec:
  targetNamespace: istio-system
  upgrade:
    preserveValues: false
  install:
    createNamespace: true
  interval: 30m
  chart:
    spec:
      chart: gateway
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: istio-system
      interval: 12h
  values:
    name: "istio-ingressgw-internal"
    serviceAccount:
      create: true
      annotations: {}
      name: "istio-ingressgw-internal"
    securityContext:
      seccompProfile:
        type: RuntimeDefault
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "subnet-aks"
