apiVersion: v1
kind: Service
metadata:
  name: opt-be-rag-memo-prompt
  namespace: opt-dev
spec:
  ports:
    - protocol: TCP
      port: 5010
      targetPort: 5010
  selector:
    app: opt-be-rag-memo-prompt
  sessionAffinity: None
  type: ClusterIP
