apiVersion: v1
kind: Service
metadata:
  name: opt-be-rag-pid-prompt
  namespace: opt-dev
spec:
  ports:
    - protocol: TCP
      port: 5060
      targetPort: 5060
  selector:
    app: opt-be-rag-pid-prompt
  sessionAffinity: None
  type: ClusterIP
