---
apiVersion: v1
kind: Service
metadata:
  name: eventstore
  namespace: opt-dev
  labels:
    app: eventstore
spec:
  ports:
  - port: 2113
    name: http
  clusterIP: None
  selector:
    app: eventstore
