apiVersion: v1
kind: ConfigMap
metadata:
  name: opt-domain-prompt-app
  namespace: opt-dev
data:
  DAPR_APP_ID: "opt-domain-prompt-app"
  DAPR_HOST : "localhost"
  DAPR_PORT: "3500"
  SERVER_HOST: "localhost"
  SERVER_PORT: "3000"
  NEXT_PRIVATE_LOCAL_WEBPACK: "true"
  NODE_ENV: "production"
  # ELASTIC_APM_SERVICE_NAME: "opt-domain-prompt-app"
  # NODE_OPTIONS: "--require=elastic-apm-node/start-next.js"
  OPTI_RAGE_SERVICE_URL: "http://opt-be-rage-process-user-query.opt-dev.svc.cluster.local:5050/query"
  OPTI_BE_TASK_EMAIL_SERVICE_URL: "http://opt-be-task-email.opt-dev.svc.cluster.local:8080"
