apiVersion: v1
kind: Service
metadata:
  name: opt-be-task-email
  namespace: opt-dev
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app: opt-be-task-email
  sessionAffinity: None
  type: ClusterIP