apiVersion: v1
kind: Service
metadata:
  name: opt-master-node-registry-query
  namespace: opt-dev
spec:
  ports:
    - name: dapr-server 
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: nestjs-query 
      protocol: TCP
      port: 5005
      targetPort: 5005
  selector:
    app: opt-master-node-registry-query
  sessionAffinity: None
  type: ClusterIP
