---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
spec:
  finalizers:
  - kubernetes
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 24h
  url: https://charts.external-secrets.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  targetNamespace: external-secrets
  upgrade:
    preserveValues: false
  install:
    createNamespace: true
  interval: 30m
  chart:
    spec:
      chart: external-secrets
      version: '0.10.x'
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: external-secrets
      interval: 12h
  values:
    fullnameOverride: external-secrets
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
