apiVersion: v1
kind: ConfigMap
metadata:
  name: opt-master-node-registry
  namespace: opt-dev 
data:
  # Common configs
  ELASTIC_APM_SERVICE_NAME: "opt-master-node-registry"
  NODE_ENV: "production"

  # Dapr configs
  DISALLOW_DAPR: "false"
  DAPR_APP_ID: "opt-master-node-registry"
  DAPR_HOST : "localhost"
  DAPR_PORT: "3500"
  SERVER_HOST: "localhost"
  SERVER_PORT: "3000"
  SECRET_STORE: "azurekeyvault"
  DB_PASS_SECRET_NAME: "opt-pg-core-password"
  
  # Command Handlers
  CH_DAPR_HOST: "localhost"
  CH_DAPR_PORT: "3500"
  CH_SERVER_HOST: "localhost"
  CH_SERVER_PORT: "3000"
  COMMAND_HANDLERS_APP_PORT: "5004"
  
  # Query Handlers
  QH_DAPR_HOST: "localhost"
  QH_DAPR_PORT: "3500"
  QH_SERVER_HOST: "localhost"
  QH_SERVER_PORT: "3000"
  QUERY_HANDLERS_APP_PORT: "5005"

  # Write database configs
  WRITE_DB_HOST: "opt-pg-core-dev-ncus.postgres.database.azure.com"
  WRITE_DB_PORT: "5432"
  WRITE_DB_USERNAME: "optadmin"
  WRITE_DB_NAME: "optimality"
  WRITE_DB_SCHEMA: "master_node_registry"

  # ReadDB configs
  READ_DB_CONNECTION_STRING: "mongodb+srv://optadmin:ntGWV9tgKAp7NHqJQGmLPZrq@opt-core-dev-ncus-pl-0.zfdut.mongodb.net/master_node_registry?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000"
