apiVersion: v1
kind: Service
metadata:
  name: opt-be-rag-bio-prompt
  namespace: opt-dev
spec:
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: opt-be-rag-bio-prompt
  sessionAffinity: None
  type: ClusterIP
