apiVersion: v1
kind: Service
metadata:
  name: opt-be-rage-process-user-query
  namespace: opt-dev
spec:
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
  selector:
    app: opt-be-rage-process-user-query
  sessionAffinity: None
  type: ClusterIP
