apiVersion: apps/v1
kind: Deployment
metadata:
  name: opt-master-node-registry-command
  namespace: opt-dev
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    app: opt-master-node-registry-command
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opt-master-node-registry-command
  template:
    metadata:
      labels:
        app: opt-master-node-registry-command
        stack: optimality
      annotations:
        dapr.io/enabled: 'true'
        dapr.io/app-id: 'opt-master-node-registry-command'
        dapr.io/app-port: '3000'
        dapr.io/sidecar-liveness-probe-delay-seconds: '10'
        dapr.io/sidecar-liveness-probe-timeout-seconds: '5'
        dapr.io/sidecar-liveness-probe-period-seconds: '20'
        dapr.io/sidecar-readiness-probe-delay-seconds: '10'
        dapr.io/sidecar-readiness-probe-timeout-seconds: '5'
        dapr.io/sidecar-readiness-probe-period-seconds: '20'
    spec:
      containers:
      - name: opt-master-node-registry-command
        image: optimality.azurecr.io/opt-master-node-registry-command:dev-0.0.1-1730110313-51 # {"$imagepolicy": "flux-system:opt-master-node-registry-command"}
        envFrom:
        - configMapRef:
            name: opt-master-node-registry
        - secretRef:
            name: opt-elastic-apm
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          # name: http
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: http
        #   initialDelaySeconds: 15
        #   periodSeconds: 10
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: http
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
