apiVersion: v1
kind: ConfigMap
metadata:
  name: opt-domain-tasks-backend
  namespace: opt-dev 
data:
  DAPR_APP_ID: "opt-domain-tasks-backend"
  DAPR_HOST : "localhost"
  DAPR_PORT: "3500"
  SERVER_HOST: "localhost"
  SERVER_PORT: "3000"
  SECRET_STORE: "azurekeyvault"
  # Database Configuration
  DB_HOST: "opt-pg-core-dev-ncus.postgres.database.azure.com"
  DB_PORT: "5432"
  DB_USER: "optadmin"
  DB_PASS_SECRET_NAME: "opt-pg-core-password"
  DB_NAME: "optimality"
  NODE_ENV: "production"
  ELASTIC_APM_SERVICE_NAME: "opt-domain-tasks-backend"