apiVersion: v1
data:
  GF_AUTH_AZUREAD_CLIENT_ID: MDIwMGY2NjQtZDViNS00OWViLWI1ODEtNGRjOWZkNDk4NDdm
  GF_AUTH_AZUREAD_CLIENT_SECRET: d352OFF+VzgxbjI5RH5tY1FOLnNsclFac2VYOFZNMFZKQTVPNmJBOA==
kind: Secret
metadata:
  name: opt-grafana
  namespace: opt-monitoring
type: Opaque
