apiVersion: v1
kind: Service
metadata:
  name: opt-be-graph-arangodb-command
  namespace: opt-dev
spec:
  ports:
    - name: dapr-server 
      protocol: TCP
      port: 80
      targetPort: 3000
    - name: nestjs-command 
      protocol: TCP
      port: 5004
      targetPort: 5004
  selector:
    app: opt-be-graph-arangodb-command
  sessionAffinity: None
  type: ClusterIP
